CREATE TABLE History (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  SenderName VARCHAR(512) NOT NULL,
  SenderAddress VARCHAR(512) NOT NULL,
  Subject VARCHAR(1024) NOT NULL,
  Body TEXT,
  Timestamp DEFAULT CURRENT_TIMESTAMP
);