CREATE TABLE Statistics (
  Subject varchar(1024) NOT NULL,
  Success INT NOT NULL DEFAULT 0,
  Error INT NOT NULL DEFAULT 0,
  Timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IDX_STATISTICS_SUBJECT ON Statistics (Subject);